# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34dd42781c90da0a574bf4893c24dabb1f7976d3f83dca8912ad7edb3e429e139887a626745277c3d950f542477368dd8842d62c752dac982aa00771a66ecca2

test:
  secret_key_base: 23b5e9d3c8007c929a54cdb1caf075d9dce26d400fab4191d1002e3c5d1e9b1320470a46d479757a42eaae1e2be65108756bf8b333035e3e4f0ea305b7c93851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
